# Generated by Django 4.2.4 on 2023-09-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='utc_offset',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
