# Generated by Django 4.2.4 on 2023-09-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_utc_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='zone_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
