# Generated by Django 4.2.4 on 2023-09-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_contact_zone_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='utc_offset',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
