# Generated by Django 4.2.4 on 2023-09-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_utc_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='offset',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='offset',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='utc_offset',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='utc_offset',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
