# Generated by Django 4.2.4 on 2023-09-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_contact_offset_profile_offset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='utc_offset',
        ),
        migrations.AlterField(
            model_name='profile',
            name='offset',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
